project:
  type: website

website:
  title: "VASTmc3"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: team.html
        text: Team
      - href: proposal.html
        text: Proposal
      - href: storyboard.html
        text: Storyboard
      - href: prototype.html
        text: Prototype

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

