project:
  type: website

website:
  title: "Reef Whispers"
  site-url: "https://reefwhispers.netlify.app/"
  bread-crumbs: false
  sidebar:
    background: "#181d31"
    logo: "images/ReefWhisperLogo.jpg"
    pinned: true
    align: center
    style: "docked"
    search: false
    collapse-level: 1
    contents:
      - icon: house-fill
        href: index.html
        text: Home
      - icon: people-fill
        href: team.html
        text: Team
      - icon: window
        href: proposal.html
        text: Proposal
      - icon: ui-checks-grid
        href: storyboard.html
        text: Storyboard
      #- href: prototype.html
      #  text: Prototype
      - href: dataprep.html 
        icon: check-circle
        text: Data Preparation
      - section: ShinyApp
        contents:
          - icon: book
            href: userguide.html
            text: User Guide
          - icon: clock-history
            href: app1.html 
            text: Temporal Pattern and Communication Network  
          - icon: virus2
            href: app2.html 
            text: Communication Clusters and Pseudonym
          - section: Time Series Analysis and Social Network graph
            icon: graph-up
            contents:
              - href: app3-overview.html
                text: Overview
              - href: app3-keywords.html
                text: Keyword Insights
              - href: app3-timeline.html
                text: Nadia’s Timeline
              - href: app3-conclusion.qmd
                text: Investigation Conclusion
        
    tools:
      - icon: house-fill
        href: index.html
        text: Home
      - icon: github
        href: "https://github.com/vriadi/VASTmc3"
        text: GitHub
        target: _blank

format:
  html:
    theme: flatly
    css: styles.css
    page-layout: full
    navigation: 
      collapse: true  # optional
      scrollToTop: true

editor: visual